/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.reto5.vista;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import practica.reto5.controlador.ControladorRequerimientos;
import practica.reto5.modelo.vo.*;

/**
 *
 * @author ediei
 */
public class RequerimientosGUI extends javax.swing.JFrame {

    // colores
    private Color negro;
    private Color rojo;
    private Color verde;
    private Color amarillo;
    private Color azul;
    private Color morado;
    private Color cyan;
    private Color gris;
    
    /**
     * Creates new form RequerimientosGUI
     */
    // ~~~~~~~~~~~~~~~~~~~~~~~~ Objeto de requerimientos ~~~~~~~~~~~~~~~~~~~~~~~~
    private final ControladorRequerimientos controlador = new ControladorRequerimientos();
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    public RequerimientosGUI() {
        initComponents();
        settings();
    }

    private void settings() {
        // contenedor
        setLocationRelativeTo(null);
        
        // creando los colores
        negro = new Color(40, 44, 52);
        rojo = new Color(224, 108, 117);
        verde = new Color(152, 195, 121);
        amarillo = new Color(229, 192, 123);
        azul = new Color(97, 175, 239);
        morado = new Color(198, 120, 221);
        cyan = new Color(86, 182, 194);
        gris = new Color(171, 178, 191);
        
        // configurando las opciones
        opciones.setForeground(negro);
        opciones.setBackground(rojo);
        opciones.setBorder(BorderFactory.createLineBorder(morado));
        
        // configurando la tabla
        tabla.setBackground(negro);
        tabla.setForeground(amarillo);
        tabla.getTableHeader().setBackground(verde);
        tabla.getTableHeader().setForeground(negro);
        tabla.getTableHeader().setFont(new Font("verdana", Font.BOLD, 12));
        tabla.setSelectionBackground(azul);
        tabla.setSelectionForeground(negro);
        
        // configurando al jscroll
        jScrollPane1.getViewport().setBackground(negro);
        jScrollPane1.setBorder(BorderFactory.createLineBorder(morado));
        jScrollPane1.setOpaque(false);
        
        // configurando el pie de pagina
        derechos.setForeground(cyan);
        derechos.setHorizontalAlignment((int)CENTER_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        opciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        derechos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RETO 5");
        setBackground(new java.awt.Color(204, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(40, 44, 52));

        opciones.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE EL REQUERIMIENTO", "REQUERIMIENTO 1", "REQUERIMIENTO 2", "REQUERIMIENTO 3" }));
        opciones.setToolTipText("ESCOJA EL REQUERIMIENTO");
        opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesActionPerformed(evt);
            }
        });

        tabla.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla.setRowHeight(25);
        jScrollPane1.setViewportView(tabla);

        derechos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        derechos.setText("DESARROLLADO POR EDIED ISAÍAS RAMOS HERNÁNDEZ");
        derechos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                derechosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                derechosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(opciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(derechos)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(derechos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesActionPerformed
        switch (opciones.getSelectedIndex()) {
            case 0:
                // mostrar tabla decoración
                tabla.setModel(new DefaultTableModel());
                break;
            case 1:
                // mostrar el primer requerimiento
                try {
                ArrayList<Requerimiento_1> lista = controlador.consultarRequerimiento1();
                String matriz_tabla[][] = new String[lista.size()][3];
                for (int i = 0; i < lista.size(); i++) {
                    matriz_tabla[i][0] = lista.get(i).getLider();
                    matriz_tabla[i][1] = lista.get(i).getCargo();
                    matriz_tabla[i][2] = lista.get(i).getProyectos() + "";
                }
                tabla.setModel(new DefaultTableModel(matriz_tabla, new String[]{"LIDER", "CARGO", "# PROYECTOS"}));
            } catch (Exception e) {
            }
            break;
            case 2:
                // mostrar el segundo requerimiento
                try {
                ArrayList<Requerimiento_2> lista = controlador.consultarRequerimiento2();
                String matriz_tabla[][] = new String[lista.size()][5];
                for (int i = 0; i < lista.size(); i++) {
                    matriz_tabla[i][0] = lista.get(i).get_id_material() + "";
                    matriz_tabla[i][1] = lista.get(i).get_nombre_material();
                    matriz_tabla[i][2] = lista.get(i).get_cantidad() + "";
                    matriz_tabla[i][3] = lista.get(i).get_precio_unidad() + "";
                    matriz_tabla[i][4] = lista.get(i).get_precio_total() + "";
                }
                tabla.setModel(new DefaultTableModel(matriz_tabla, new String[]{"ID MATERIAL", "NOMBRE MATERIAL", "CANTIDAD", "PRECIO UNIDAD", "PRECIO TOTAL"}));
            } catch (Exception e) {
            }
            break;
            case 3:
                // mostrar el tercer requerimiento
                try {

                ArrayList<Requerimiento_3> lista = controlador.consultarRequerimiento3();
                String matriz_tabla[][] = new String[lista.size()][4];
                for (int i = 0; i < lista.size(); i++) {
                    matriz_tabla[i][0] = lista.get(i).get_id_proyecto() + "";
                    matriz_tabla[i][1] = lista.get(i).get_ciudad();
                    matriz_tabla[i][2] = lista.get(i).get_clasificacion();
                    matriz_tabla[i][3] = lista.get(i).get_costo_proyecto() + "";
                }
                tabla.setModel(new DefaultTableModel(matriz_tabla, new String[] {"ID PROYECTO", "CIUDAD", "CLASIFICACION", "COSTO PROYECTO"}));
            } catch (Exception e) {
            }

            break;
        }
    }//GEN-LAST:event_opcionesActionPerformed

    private void derechosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derechosMouseEntered
        derechos.setForeground(amarillo);
    }//GEN-LAST:event_derechosMouseEntered

    private void derechosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derechosMouseExited
        derechos.setForeground(cyan);
    }//GEN-LAST:event_derechosMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel derechos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> opciones;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
